version: '3.6'

services:
  gateway:
    restart: always
    image: envoyproxy/envoy:v1.10.0
    volumes:
      - ../config/gateway:/etc/envoy/
    command: /usr/local/bin/envoy -l info -c /etc/envoy/envoy.yaml
    labels:
      - "traefik.http.routers.gateway-opendax.rule=Host(`www.app.local`) && PathPrefix(`/api`,`/admin`,`/assets/`)"
      - "traefik.enable=true"
      - "traefik.http.services.gateway-opendax.loadbalancer.server.port=8099"
      - "traefik.http.routers.gateway-opendax.entrypoints=web"
